apiVersion: v1
kind: Service

metadata:
  name: app-services

spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: wikimedia
---


apiVersion: app/v1
kind: Deployment
metadata:
  name: wikimedia-deployment
  labels:
    app: wikimedia
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: wikimedia
    spec:
      containers:
        - name: wikimedia
          image: wikimedia6010.azurecr.io/wikimedia
          ports:
            - containerPort: 80
              name: httpd-port
          env:
            - name: WIKIMEDIA_DB_HOST
              value: mariadb-service
            - name: WIKIMEDIA_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mediawiki-secrets
                  key: dbuser
            - name: WIKIMEDIA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediawiki-secrets
                  key: dbpassword
            - name: WIKIMEDIA_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mediawiki-secrets
                  key: dbname

